---
consumer_secret: <%= NOCRAP_TWITTER_CONSUMER_KEY %>
consumer_token: <%= NOCRAP_TWITTER_CONSUMER_SECRET %>
callback_urls:
  production: http://nocrap.heroku.com/twitter/auth
  development: http://localhost:3000/twitter/auth